package it.polimi.se2019.view.client.cli;

public enum CliState {
    ACTIONSELECTION,
    POWERUPCONVERTING,
    POWERUPCHOOSING,
    WEAPONSCHOOSING,
    PLATFORMSCHOOSING,
    WEAPONSWITCHING,
    TARGETSHOWING,
    EFFECTSSHOWING,
    OPTIONSHOWING,
    WEAPONSRELOADING,
    WEAPONSUSING,
    POWERUPSUSING,
    AMMODISCARTING
}
